create database lab1
on(
	NAME = 'lab1',
	FILENAME = 'D:\Sql\lab1.mdf',
	SIZE = 10MB,
	MAXSIZE = 50MB,
	FILEGROWTH = 10MB
)
LOG ON(
	NAME = 'Loglab1',
	FILENAME = 'D:\Sql\lab1.ldf',
	SIZE = 3MB,
	MAXSIZE = 30MB,
	FILEGROWTH = 3MB	
)

COLLATE Cyrillic_General_CI_AS

use lab1


create table FACULTY(
	FacNo INTEGER,
	[NAME] CHAR(20),
	BUILDING CHAR(5)
	)

CREATE TABLE DEPARTMENT(
	DepNO INTEGER,
	FacNo INTEGER,
	NAME VARCHAR(50),
	HEAD VARCHAR(50),
	BUILDING DECIMAL(2),
	FUND DECIMAL(7,2)
	)

CREATE TABLE TEACHER(
	TchNO INTEGER,
	DePNo INTEGER,
	NAME VARCHAR(50),
	POST VARCHAR(20),
	TEL CHAR(2),
	HIREDATE DATE
	)

CREATE TABLE SGROUP(
	GrpNO INTEGER,
	DePNo INTEGER,
	COURSE CHAR(1),
	NUM CHAR(3),
	QUANTITY DECIMAL(2),
	CURATOR INTEGER
	)

CREATE TABLE [SUBJECT](
	SbJNO INTEGER,
	NAME VARCHAR(50),
	)


CREATE TABLE ROOM(
	RoomNO INTEGER,
	NUM DECIMAL(4),
	SEATS DECIMAL(3)
	)

CREATE TABLE LECTURE(
	TchNO INTEGER,
	GrpNo INTEGER,
	SbjNo INTEGER,
	RomNo INTEGER,
	[TYPE] VARCHAR(25),
	[DAY] CHAR(10),
	[WEEK] DECIMAL(1)
	)

--CHANGE TABLE FACULTY
ALTER TABLE FACULTY
ALTER COLUMN [NAME] VARCHAR(50)

ALTER TABLE FACULTY
ADD DAEN VARCHAR(50)

ALTER TABLE FACULTY  
ADD FUND decimal(7,2)

--CHANGE TABLE DEPARTMENT
ALTER TABLE DEPARTMENT   
ALTER COLUMN BUILDING char(5)

--CHANGE TABLE TEACHER 
ALTER TABLE TEACHER 
ADD SALARY decimal(6,2)

ALTER TABLE TEACHER   
ADD COMMISION decimal(6,2)

--CHANGE TABLE SGROUP

ALTER TABLE SGROUP
ALTER COLUMN COURSE DECIMAL(1)
			

ALTER TABLE SGROUP
ALTER COLUMN NUM DECIMAL(3)

ALTER TABLE SGROUP
ADD RATING DECIMAL(3)


--CHANGE TABLE ROOM
ALTER TABLE ROOM
ADD [FLOOR] DECIMAL(2)

ALTER TABLE ROOM
ADD BULDING CHAR(5)

--CHANGE TABLE LECTURE 
ALTER TABLE LECTURE
ADD LESSON DECIMAL(1)

ALTER TABLE LECTURE
ALTER COLUMN [DAY] CHAR(3)





